# Numpy

Numpy is a general-purpose array-processing package. It provides a high-performance multi-dimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.

### What is an array?

An array is a data Structure that stores values of same data types.So, we can  do update , add , access and remove into arrays. 

In [1]:
# import numpy

import numpy as np

In [2]:
list_1 = [1,2,3,4]
arr = np.array(list_1)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr
# print(arr)

array([1, 2, 3, 4])

In [5]:
# Shape -- it specifies how many no of rows and columns are there in arr.

arr.shape

(4,)

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2.shape

(2, 3)

In [8]:
# reshape -- It takes no of rows and columns as a values and convert arr into that rows and columns.

# It only convert into total no values we have (cell 19 for exmaple).

arr3 = np.array([[1,2,3,4,5],[6,7,8,9,1],[2,3,4,5,6]])
arr3

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6]])

In [9]:
arr3.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3.reshape(4,3)

ValueError: cannot reshape array of size 15 into shape (4,3)

## Indexing

In [11]:
#  Accessing the array elements

arr = np.array([1,2,3,4,5,6])


In [12]:
arr[3]  # Accessing value from index value

4

In [30]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [31]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [32]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [ ]:
# arange -- It create 1-D array and It takes range from lower value to upper value and take step gap.

arr = np.arange(0,10)
arr

In [ ]:
# linspace -- It create 1-D aaray and it takes range from lower value to upper value and also take how many points you want to print.
value = np.linspace(1,10,20)
value

In [14]:
# Copy() function and broadcasting

# copy function helps that it will not change original arr after copy 

arr = np.array([1,2,3,4])
arr1 = arr.copy()
arr1[2:] = 20
print(arr1)
print(arr)


[ 1  2 20 20]
[1 2 3 4]


In [18]:
# Some conditions are very useful in Exploratory Data Analysis.

arr = np.array([1,2,3,4,5])

arr<3
[arr/2]


[array([0.5, 1. , 1.5, 2. , 2.5])]

In [20]:
# Creating array and reshaping 
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
# Ones and Zeros -- It will create array of values with 1 and 0 respectively and it also take datatype.

np.ones(4,dtype=int)


array([1, 1, 1, 1])

In [22]:
np.ones((2,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros(4,dtype)

array([0., 0., 0., 0.])

In [24]:
# Random Distribution

np.random.rand(3,3)

array([[0.5705048 , 0.91870338, 0.55856765],
       [0.73424179, 0.64083361, 0.90865419],
       [0.29564491, 0.8825264 , 0.30657526]])

In [26]:
arr_n = np.random.randn(4,4)
arr_n

array([[ 0.32941943, -0.91898792,  0.05876657, -0.98169668],
       [-0.36441675,  0.10966314,  1.36766374,  1.65664007],
       [-0.21384214, -0.50942436, -1.96781266,  0.14865901],
       [-0.22642688, -0.22402958, -1.15468532,  0.52729886]])

In [27]:
arr_p = np.random.randint(0,100,8).reshape(2,4)
arr_p

array([[53, 70, 85, 43],
       [19, 20, 65, 75]])

In [28]:
np.random.random_sample((1,5))

array([[0.03323817, 0.15009392, 0.32283739, 0.63286146, 0.96517592]])