# Numpy

Numpy is a general-purpose array-processing package. It provides a high-performance multi-dimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.

### What is an array?

An array is a data Structure that stores values of same data types.So, we can  do update , add , access and remove into arrays. 

In [1]:
# import numpy

import numpy as np

In [2]:
list_1 = [1,2,3,4]
arr = np.array(list_1)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr
# print(arr)

array([1, 2, 3, 4])

## Shape and Reshape

* shape--It specifies how many no of rows and columns are there in arr.

* reshape--It takes no of rows and columns as a values and convert arr into that rows and columns

In [5]:
arr.shape

(4,)

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2.shape

(2, 3)

In [8]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,1],[2,3,4,5,6]])
arr3

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 6]])

In [9]:
arr3.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

## Indexing

In [10]:
#  Accessing the array elements

arr = np.array([1,2,3,4,5,6])


In [11]:
arr[3]  # Accessing value from index value

4

In [12]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [14]:
arr[1:2,1:4]

array([[3, 4, 5]])

## Arange, linspace and Copy function

* Arange -- It create 1-D array and It takes range from lower value to upper value and take step gap.

* linspace -- It create 1-D aaray and it takes range from lower value to upper value and also take how many points you want to print.

* copy -- copy function helps that it will not change original arr after copy

In [15]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
value = np.linspace(1,10,20)
value

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [17]:
arr = np.array([1,2,3,4])
arr1 = arr.copy()
arr1[2:] = 20
print(arr1)
print(arr)


[ 1  2 20 20]
[1 2 3 4]


In [18]:
# Some conditions are very useful in Exploratory Data Analysis.

arr = np.array([1,2,3,4,5])

arr<3
[arr/2]


[array([0.5, 1. , 1.5, 2. , 2.5])]

In [19]:
# Creating array and reshaping 
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## Ones and Zeros

* It will create array of values with 1 and 0 respectively and it also take datatype.

In [20]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [21]:
np.ones((2,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

## Random Functions 

In [23]:
np.random.rand(3,3)

array([[0.36825043, 0.3487275 , 0.73651134],
       [0.90336791, 0.58898007, 0.54592465],
       [0.75248382, 0.78879687, 0.321429  ]])

In [24]:
arr_n = np.random.randn(4,4)
arr_n

array([[-0.74464338, -1.16350405, -1.14898363, -0.65545576],
       [ 0.49630878,  0.11933696,  2.08769639, -1.44674711],
       [ 1.12364776,  0.16318402,  0.0570382 ,  1.19571191],
       [-1.06411957, -0.32114055,  1.6468638 ,  0.64535102]])

In [25]:
arr_p = np.random.randint(0,100,8).reshape(2,4)
arr_p

array([[82, 43, 35, 14],
       [76, 16, 70, 83]])

In [26]:
np.random.random_sample((1,5))

array([[0.98955819, 0.63227426, 0.08508564, 0.03750657, 0.20174546]])

## Transpose and Flatten

* Transpose -- by using this we can transpose the array and it will not affect the original array but it will create a new array.

* Flattern -- It creates a copy of the input array flatterned to one dimension.


In [27]:
arr_t = np.array([[1,2,3],[4,5,6]])
res = np.transpose(arr_t)
print(res)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
res1 = arr_t.flatten()
print(res1)

[1 2 3 4 5 6]


## Concatenate

Two or more arrays can be joined together using the concatenate function with a tuple of the arrays to be joined.

If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default, it is along the first dimension.

In [29]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([2,3,4,5])
res = np.concatenate((arr_1,arr_2))
print(res)

[1 2 3 4 2 3 4 5]


In [30]:
arr_1 = np.array([[1,2,3],[0,9,0]])
arr_2 = np.array([[4,5,6],[6,7,9]])
res = np.concatenate((arr_1,arr_2),axis=1)
print(res)

[[1 2 3 4 5 6]
 [0 9 0 6 7 9]]


## Identity and Eye

* Identity -- The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as  and the rest as . The default type of elements is float.


* Eye -- The eye tool returns a 2-D array with 's as the diagonal and 's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter . A positive  is for the upper diagonal, a negative  is for the lower, and a 0 k(default) is for the main diagonal.

In [31]:
np.set_printoptions(legacy="1.13")  #In order to get alignment correct and gap betwwwn values

res = np.identity(3)  # 3 is for dimension
print(res)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [32]:
np.set_printoptions(legacy="1.13")

res= np.eye(5,5,k=1)  # 5X5 dimensional array with upper diagonal
print(res)

[[ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]


## Mathematics Functions 

1) Add, Subtract, multiply, divide (Floor,ceil,rint) , mod, power

2) Min and Max

3) Sum and Product

In [33]:
a = np.array([1,2,3,4],dtype=float)   # You can take any data type 
b = np.array([5,6,7,8],dtype=float)

res1 = np.add(a,b)      # we can also do simple function a+b
res2 = np.subtract(a,b) # we can also do simple function a-b
res3 = np.multiply(a,b) # we can also do simple function a*b
res4 = np.divide(a,b)   # we can also do simple function a/b
res5 = np.mod(a,b)      # we can also do simple function a%b
res6 = np.power(a,b)    # we can also do simple function a**b
print(res1,res2,res3,res4,res5,res6,sep="\n")

[  6.   8.  10.  12.]
[-4. -4. -4. -4.]
[  5.  12.  21.  32.]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 1.  2.  3.  4.]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


In [34]:
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
res1 = np.floor(arr)
res2 = np.ceil(arr)
res3 = np.rint(arr)
print(res1,res2,res3,sep="\n")

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [35]:
arr = np.array([[1,2],[3,4],[5,6]])

res1 = np.min(arr,axis=0)
res2 = np.min(arr,axis=1)
print(res1,res2,sep="\n")

res3 = np.max(arr,axis=0)
res4 = np.max(arr,axis=1)
print(res3,res4,sep="\n")

[1 2]
[1 3 5]
[5 6]
[2 4 6]


In [36]:
arr = np.array([ [1, 2], [3, 4] ])

res1 = np.sum(arr,axis=0)
res2 = np.sum(arr,axis=1)
print(res1,res2,sep="\n")

res3 = np.prod(arr,axis=0)
res4 = np.prod(arr,axis=1)
print(res3,res4,sep="\n")

[4 6]
[3 7]
[3 8]
[ 2 12]


## Mean , Variance and Standard Deviation

* Mean -- It computes the arithmetic mean along the specified axis.

* Variance -- It computes the arithmetic variance along the specified axis.

* Standard Deviation -- It computes the arithmetic standard deviation along the specified axis.

In [37]:
arr = np.array([[1,2],[3,4]])

# Mean 
res1 = np.mean(arr,axis=0)
res2 = np.mean(arr,axis=1)
print(res1,res2,sep="\n")

# Variance 
res3 = np.var(arr,axis=0)
res4 = np.var(arr,axis=1)
print(res3,res4,sep="\n")

# Standard Deviation
res5 = np.std(arr,axis=0)
res6 = np.std(arr,axis=1)
print(res5,res6,sep="\n")

[ 2.  3.]
[ 1.5  3.5]
[ 1.  1.]
[ 0.25  0.25]
[ 1.  1.]
[ 0.5  0.5]


## Vector Products -- Dot, Cross, Inner and Outer

* Dot -- The dot tool returns the dot product of two arrays.

* Cross -- The cross tool returns the cross product of two arrays.

* Inner -- The inner tool returns the inner product of two arrays.

* Outer -- The outer tool returns the outer product of two arrays

In [38]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[4,5]])
res = np.dot(a,b)  # DOT Product
print(res)

res1 = np.cross(a,b) # Cross Product
print(res1)

[[11 14]
 [25 32]]
[-2 -1]


In [39]:
A = np.array([0, 1])
B = np.array([3, 4])
res1 = np.inner(A,B)  # INNER Product
res2 = np.outer(A,B)  # Outer Product

print(res1,res2,sep="\n")

4
[[0 0]
 [3 4]]


## Polynomials -- poly, roots, ployint, ployder, ployval and ployfit

* poly -- The poly tool returns the coefficients of a polynomial with the given sequence of roots.

* roots -- The roots tool returns the roots of a polynomial with the given coefficients.

* polyint -- The polyint tool returns an antiderivative (indefinite integral) of a polynomial.

* polyder -- The polyder tool returns the derivative of the specified order of a polynomial.

* polyval -- The polyval tool evaluates the polynomial at specific value.

* polyfit -- The polyfit tool fits a polynomial of a specified order to a set of data using a least-squares approach.


Note -- The functions polyadd, polysub, polymul, and polydiv also handle proper addition, subtraction, multiplication, and division of polynomial coefficients, respectively.

In [40]:
arr = np.array([1,-1,2,-4])
res1 = np.poly(arr)
res2 = np.roots([1,0,-1])
res3 = np.polyint(arr)
res4 = np.polyder(arr)
res5 = np.polyval(arr,3)
res6 = np.polyfit(arr,[1,2,-3,5],2)

print(res1,res2,res3,res4,res5,res6,sep="\n")


[ 1.  2. -9. -2.  8.]
[ 1. -1.]
[ 0.25       -0.33333333  1.         -4.          0.        ]
[ 3 -2  2]
20
[-0.15909091 -1.50757576  1.37121212]


## Linear Algebra -- linalg.det, linalg.eig, linalg.inv 

* linalg.det -- The linalg.det tool computes the determinant of an array.

* linalg.eig -- The linalg.eig computes the eigenvalues and right eigenvectors of a square array.

* linalg.inv -- The linalg.inv tool computes the (multiplicative) inverse of a matrix.


In [41]:
arr = np.array([[1,2],[2,1]])

# linalg.det
res1 = np.linalg.det(arr)
print(res1)

# linalg.eig 
vals,vecs = np.linalg.eig(arr)
print(vals,vecs,sep="\n")

# linalg.inv
res2 = np.linalg.inv(arr)
print(res2)

-3.0
[ 3. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]
